import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';
import Header from './Header';


export default function Home() {
    return (
       <div>
 <Head>
                <title>Add a New Event</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href ="/favicon.ico"/>
            </Head>

            <main className="h-screen flex items-center justify-center">
            <form className="bg-#feffdf flex rounded-1g w-1/2 font-latoRegular"></form>
                <div className="flex-1 text-black-700 p-20">
                    <div className="mt-6">
                        {/*EventName input field*/ }
                        <div className="pb-4"> 
                        <label htmlFor="Event Name">Event Name
                     */Event Name */ 
                     </label>
                     <input 
                     className="border-2 border-black-500 p-2 rounded-md w-1/2 focus:border"
                     type="text"
                     name="name"
                     placeholder="Horrifying Haunted House"
                     />

                    </div>

                    <div className="mt-6">
                        {/*EventAddress input field*/ }
                        <div className="pb-4"> 
                        <label htmlFor="Event Name">Address
                        */ Address */
                        </label>
                        <input 
                     className="border-2 border-black-500 p-2 rounded-md w-1/2 focus:border"
                     type="text"
                     name="Address"
                     placeholder="666 Spooky Ave"
                     />
                    </div> 

                    <div className="mt-6">
                        {/*EventDate input field*/ }
                        <div className="pb-4"> 
                        <label htmlFor="Event Name">
                            */Date*/
                            </label>
                            <input 
                     className="border-2 border-black-500 p-2 rounded-md w-1/2 focus:border"
                     type="text"
                     name="Date"
                     placeholder="10/31/2023"
                     />
                    </div>
                    </div>
                    </div>
                    </div>
                    </div>
                
function sayUpdate() {
  alert('Update!')
}
<button onClick={sayUpdate}>Update</button>;

            </main>
        </div>

  );  }
   
  
